name: Release Build and Push

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: cjowood/ynab-receipt-uploader

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract version parts
      id: version
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        echo "FULL=$TAG" >> $GITHUB_OUTPUT
        echo "MINOR=$(echo $TAG | sed -E 's/^v([0-9]+\.[0-9]+)\.[0-9]+$/v\1/')" >> $GITHUB_OUTPUT
        echo "MAJOR=$(echo $TAG | sed -E 's/^v([0-9]+)\.[0-9]+\.[0-9]+$/v\1/')" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push release image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.FULL }}
          ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.MINOR }}
          ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.MAJOR }}
          ${{ env.IMAGE_NAME }}:latest
        build-args: |
          VERSION=${{ steps.version.outputs.FULL }}
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max